general:
  runs:
    as_job: true
file_extensions:
  model: mod
  output: lst
tools:
  modelfit:
    method: pharmpy
    console: true
  bootstrap:
    method: pharmpy
    samples: 500
  vpc:
    method: pharmpy
    samples: 500
