general:
  list:
    columns:
      id: true
      reference: false
      description: true
      tag: false
      notes: true
      tools: true
      status: true
      ofv: true
      finished: true
  runs:
    as_job: true

file_extensions:
  model: mod
  output: lst

tools:
  modelfit:
    method: pharmpy
    console: true
  bootstrap:
    method: pharmpy
    samples: 500
  vpc:
    method: pharmpy
    samples: 500
