tools:
  nmfe_wrapper:
    method: nmfe|pharmpy|psn
    console: true|false # only affects `nmfe` method
  bootstrap:
    method: pharmpy|psn
    samples: 500
  vpc:
    method: pharmpy|psn
    samples: 500
files:
  folder_name: run_name|run_name_sequential
  run_prefix: run|mod|...
file_extensions:
  model: mod|ctl|...
  output: lst|res|...

